-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgb/UsA+Q2tR7x1qqg
KcbEDXr5s+LgZwAkHH1jn7ggxjOgCgYIKoZIzj0DAQehRANCAATEY6JC9jCzkmBR
ucrFSLLBUj7HRQZqgdtYAqTC0y1y9EU1bcpAi+9Io1Fc5xjxCIGjK45zDshgWhJZ
yNGLVRE+
-----END PRIVATE KEY-----