-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHn9bA4TpN25OuQbS
C/vkil96K6mEvfCQl6QwmE2RsrigCgYIKoZIzj0DAQehRANCAASjfAdJZVpjJlpD
KlGHgMCeccsrQ4LvDE84Qpn+VI+wr3gu2qdEuA+eSR0flm3q2tr/8Uo4WCyYCnm9
EyKAtDb+
-----END PRIVATE KEY-----