-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgvc+JUiGAQvE3YTpH
LNXZFheMOdkFmkLA6X7ju5N1bgegCgYIKoZIzj0DAQehRANCAAQ9FvAVl8KdggFc
HN5o65DH0TPnVxhxQgPPiQSqot206bxuGP9eFhY4TmJT/QitaKQDQGiarNesuSOe
JZgV4A7q
-----END PRIVATE KEY-----