-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgI7MhH7mkAsMVixDw
0L3un4ZNLJC/YB6pwv1GUXJoGaGgCgYIKoZIzj0DAQehRANCAAQGnsrvKUxu0dQY
9wADF8KD2c1mOsMFDzHW29RYJpOmSspwWLNKUJsX7nswE7EZqSCW7Z4EwmaaeWRe
GXdQlEhU
-----END PRIVATE KEY-----