-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBXrBf4FaWBusroxF
0RzpbTuDIJKNdYwOgu1CtT1Q40KgCgYIKoZIzj0DAQehRANCAATUY1LltRZtrXhH
xIY4nyw7fPjUklLXpON4Rt0QWc5MbcbRYuYVzYrC5FB9O2UR0yI1af9FgkaFWB8Q
d+dlYAFJ
-----END PRIVATE KEY-----