-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgD1e7jl8C6M/VtxQ3
pri8ziKAW9wyrD+W0ebrPZ/axBWgCgYIKoZIzj0DAQehRANCAARFtb+vaUxzZQck
RmxiHnw+uF3A2jy0UjP2PzQzdk8/aMQJ80+yIatSZXL6TsMbQtzIi1bdhVDt4Sit
5ZUL3CHW
-----END PRIVATE KEY-----