-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtdS2jLN0TlB84bWg
7F0RRmS5wYTlOfpDQkg2Y1k8DEGgCgYIKoZIzj0DAQehRANCAATttmpJNwh3zCH2
qhqJUlNpNTlLadxZvaYano+EA+Kib53mjdusPp38OwOha4TQBxEwfRIKKqSdf0/T
gGcZoe5Z
-----END PRIVATE KEY-----