-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUvWCsfe8kq5YJcLZ
JZIWs7v4QVfx+TQCv9W+fKWNTy2gCgYIKoZIzj0DAQehRANCAASnZqEWWcOPs5vr
3Yp2FtdxKaWeNqmwd9jO+qPWaK6McaljN7UlxAvgTl87YvVKB/NFvN0z50Eaz+yU
LJBeXPQw
-----END PRIVATE KEY-----