-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgueZypxT6Oy6GOxXs
xrZht0Pi4BYBcfodDqVL6DiwG4KgCgYIKoZIzj0DAQehRANCAASltpPSd9bYk5DN
PaGKmHWeEcLuzWYpqoR8Kkp/u3+5nUrLUi3hJ4aK8LbNQeHdZjIoOC5S7i6RwYnB
xvBCBbuQ
-----END PRIVATE KEY-----