-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQggNGl+TdyxuZqIpEl
Ec5ZjB66Qku92NfxOAFVExg+0FugCgYIKoZIzj0DAQehRANCAAQpl5Fxf/DZL6AU
Oq9oLpxs9ikHywDtxmfvRvZ5K0h8/nYAn+JUdIxZRP4v8LCIHu99Loi1wFTwoUuD
1l2ilz+I
-----END PRIVATE KEY-----