-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkM/eA+THIrZZXItd
9+/9YTFa6+3vIdVz8DKPRciOmWygCgYIKoZIzj0DAQehRANCAARKp+H+KDRXstxn
BgihnmfWoOC2UWC/iFJtBYZNZbhZLfIwiP/S4PXe3kY2t/VVCOMctnlVgo0vxP5V
9vsEe59S
-----END PRIVATE KEY-----