-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg9E5NpYkDJRO/0fgJ
zL2d6elLMlwWIFOE7glAovkoonWgCgYIKoZIzj0DAQehRANCAASTz99XABXKtSI8
Mj47siUDo/V+uCBw5cRdsZqFAqh+CKEeT3Vn+vycXVnGsn12oReimgYmg+ftcDaK
75YslIQM
-----END PRIVATE KEY-----