-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgPq/FAFPAWdFVKG0a
A0Vm3g1gsM2n16B3dK5CWsZ+iVqgCgYIKoZIzj0DAQehRANCAARuZE/IJcuIRWJb
Gp4jwV99bfWoZVmnhDMqCIDOHUYsh5HQinIVoXaVDsycwl0yYg4vOMzPt7dTlAzp
xtXX73sp
-----END PRIVATE KEY-----