-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg+vlk+0nqKi5oJTj7
vuf9if2OQtDlHjT1ZEZgEc/aUkmgCgYIKoZIzj0DAQehRANCAAT3UWaUe+r2F4xk
HFieYu6PL6dKSeJc5KqfmX+kjErRVaKQEsFwHe/uA0i1GDteixCUAjaE4ZxfvVUM
ItPR3iES
-----END PRIVATE KEY-----