-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtXDsrZvLt/wmoWMG
DcDzTNWXbwE5wHLBZED4K+9swAigCgYIKoZIzj0DAQehRANCAAR0zMrjB/FHt0tH
viSvZutn7diU0APLig32SFuUO4uikUtFohKl+/k7O2LEG0tsOx9LNG/h5amjxbid
aAh85Qqe
-----END PRIVATE KEY-----