import {requireNativeComponent} from 'react-native';

export default {
  analyctiSelected: require('../assets/images/ic_analyctis_selected.png'),
  analyctiNonselected: require('../assets/images/ic_analytics.png'),
  forwordArrow:require('../assets/images/ic_arrow.png'),
  backArrow:require('../assets/images/ic_back.png'),
  bikeNonSelected:require('../assets/images/ic_bike.png'),
  bikeSelected:require('../assets/images/ic_bike_b.png'),
  call:require('../assets/images/ic_call.png'),
  carNonSelectd:require('../assets/images/ic_car.png'),
  carSelectd:require('../assets/images/ic_car_b.png'),
  chatBlue:require('../assets/images/ic_chat_blue.png'),
  chatSelected:require('../assets/images/ic_chat_selected.png'),
  chatNonSelected:require('../assets/images/ic_chat.png'),
  codeInactive:require('../assets/images/ic_code_grey.png'),
  codeActive:require('../assets/images/ic_code.png'),
  crossRed:require('../assets/images/ic_cross_red.png'),
  cycleInactive:require('../assets/images/ic_cycle.png'),
  cycleActive:require('../assets/images/ic_cycle_b.png'),
  listMenu:require('../assets/images/ic_list.png'),
  locationOff:require('../assets/images/ic_location_off.png'),
  locationOn:require('../assets/images/ic_location_on.png'),
  logout:require('../assets/images/ic_Logout.png'),
  map:require('../assets/images/ic_map.png'),
  menu:require('../assets/images/ic_menu.png'),
  notesBlue:require('../assets/images/ic_notes_blue.png'),
  notes:require('../assets/images/ic_notes.png'),
  offDuty:require('../assets/images/ic_off_duty.png'),
  path:require('../assets/images/ic_path.png'),
  photoBlue:require('../assets/images/ic_photo_blue.png'),
  photoInactive:require('../assets/images/ic_photo.png'),
  radioActive:require('../assets/images/ic_radio1.png'),
  radioInactive:require('../assets/images/ic_radio2.png'),
  settingsIcon:require('../assets/images/ic_settings.png'),
  signatureBlue:require('../assets/images/ic_signature_blue.png'),
  signature:require('../assets/images/ic_signature.png'),
  support:require('../assets/images/ic_support.png'),
  taskHistory:require('../assets/images/ic_task_history.png'),
  noTask:require('../assets/images/ic_task_no.png'),
  taskSelected:require('../assets/images/ic_task_selected.png'),
  tickGreen:require('../assets/images/ic_tick_green.png'),
  time:require('../assets/images/ic_time.png'),
  truckInactive:require('../assets/images/ic_truck.png'),
  truckActive:require('../assets/images/ic_truck_b.png'),
  tutorial:require('../assets/images/ic_tutorial.png'),
  walk:require('../assets/images/ic_walk.png'),
  walkBlue:require('../assets/images/ic_walk_b.png'),
  pinBlue:require('../assets/images/ico_pin_blue.png'),
  logo:require('../assets/images/Main_logo.png'),
  pinRed:require('../assets/images/ic_pin.png'),
  dollor:require('../assets/images/ic_dollar.png'),
  customer:require('../assets/images/ic_customer.png'),
  details:require('../assets/images/ic_details.png'),
  task:require('../assets/images/ic_task.png'),
  task_green_tik:require('../assets/images/ic_tick.png'),
  blue_tik:require('../assets/images/ic_tick2.png'),
  redioUnSelectedButton:require('../assets/images/ic_radiobutton.png'),
  redioSelectedButton:require('../assets/images/ic_radiocheck.png'),
  profileImage:require('../assets/images/ic_profile.png'),
  wallet:require('../assets/images/ic_wallet.png'),

  
};
