require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'


abstract_target 'available_pods' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  rn_maps_path = '../node_modules/react-native-maps'
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'
  pod 'ZendeskChatSDK'
  pod'ZendeskChatProvidersSDK'


#RoyoDriverApp Target
target 'RoyoDriverApp' do
  
end


#Runrun Target
target 'Runrun' do
  
end
  
  #Deliverstat Target
target 'Deliverstat' do

end


#AfricanVillageMarket Target
target 'AfricanVillageMarket' do
  
end


#Africanize Target
target 'Africanize' do
  
end


#Tranzit Target
target 'Tranzit' do
  
end



#Hemptify Target
target 'Hemptify' do
  


end


#Goody Target
target 'Goody' do
  


end


#YogoFood Target
target 'YogoFood' do
  


end



#Arena_Grub Target
target 'Arena_Grub' do
  


end



#BottomsUp Target
target 'BottomsUp' do
  


end


#BlipDelivery Target
target 'BlipDelivery' do
  


end



#BustanFakieh Target
target 'BustanFakieh' do
  


end


#Codiner Target
target 'Codiner' do
  


end

#BustanFakieh Target
target 'Elog' do
  


end


#Cabdelivr Target
target 'Cabdelivr' do
  


end


#Drivree Target
target 'Drivree' do
  


end


#SeaChangeVending Target
target 'SeaChangeVending' do
  


end


#Rxnow Target
target 'Rxnow' do
  


end


# #OrderChekcout Target
target 'Ordercheckout' do
  


end

#Noki Target
target 'Noki' do
  


end


#Ored Target
target 'Ored' do
  


end


#Yummidash Target
target 'Yummiidash' do
  


end


#YourLaundryApp Target
target 'YourLaundryApp' do
  


end


# #ZuzuClean Target
target 'ZuzuClean' do
  

end



#LoopWhole Target
target 'LoopWhole' do
  

end





#Donepacked Target
target 'Donepacked' do
  


end


#CareWorks Target
target 'CareWorks' do
  


end

#ThubaeRides Targetfz
target 'ThubaeRides' do
  


end


#Menus Target
target 'Menus' do
  
end

#Maxis Delivery Target
target 'MaxisDelivery' do
  
end


#WH Target
target 'WH' do
  
end

#Elcheregio Target
target 'Elcheregio' do
  
end

#Hmc Target
target 'Hmc' do
  
end

#ExpressDeliverys Target
target 'ExpressDeliverys' do

end

#BotSeat Delivery Target
target 'BotSeat' do
  
end
  
  #MokabFix Delivery Target
target 'MokabFix' do
  
end
  
  #PinkJet Delivery Target
target 'PinkJet' do
  
end
  
#Spidbi Delivery Target
target 'Spidbi' do
  
end

#Fleety Delivery Target
  target 'Fleety' do
    
  end


#Gumastas Delivery Target
  target 'Gumastas' do
    
  end

#Dishefs Delivery Target
  target 'Dishefs' do
    
  end

 #Govachow Target
   target 'Govachow' do
    
   end



#Bilionza Target
  target 'Bilionza' do
    
  end


#GoKab Target
  target 'GoKab' do
    
  end


#Bezalio Target
  target 'Bezalio' do
    
  end

#DoleyPharmacy Target
  target 'DoleyPharmacy' do
  

  end

#Jetrider Target
  target 'Jetrider' do
    
  end


#Drus Target
  target 'Drus' do
    
  end

#EquMD Target
  target 'EquMD' do
    
end

#Klickmat Target
  target 'Klickmat' do
    
  end

#InstaShop Target
  target 'InstaShop' do
    
  end

#Tranznet Target
  target 'Tranznet' do
    
  end


#AgriOnlineRider Target
target 'AgriOnlineRider' do
  
end


#Grub Target
target 'Grub' do
  
end
  
#YouChillax Target
target 'YouChillax' do
    
end

#HelpNowRightNow Target
target 'HelpNowRightNow' do
  
end


#Taquick Target
  target 'Taquick' do
    

    end


#SirVU Target
  target 'SirVU' do
    

    end



#Somame Target
  target 'Somame' do
    

    end


#ClickEat Target
  target 'ClickEat' do
    

    end


#Punnet Target
  target 'Punnet' do
    
  end
#ShooraFresh Target
  target 'ShooraFresh' do
    

    end


#Click2Deliver Target
  target 'Click2Deliver' do
    

    end

#TruckTireNow Target
  target 'TruckTireNow' do
    
    end


#Voltaic Target
  target 'Voltaic' do
    
    end
    
  
      
#Ace Target
  target 'Ace' do
    

    end



#Zest Target
  target 'Zest' do
    

    end


#Elixir Target
  target 'Elixir' do
    

    end
#Gusto Target
  target 'Gusto' do
    

    end

#Suel Target
  target 'Suel' do
    

    end
#Homeric Target
  target 'Homeric' do
    

    end


  #Share Target
  target 'Share' do
    

    end
    #Yeboy Target
  target 'Yeboy' do
    

    end
    
  
  #MoboErrandsService Target
  target 'MoboErrandsService' do
    

    end

#360Kel Target
target '360Kel' do
  

  end

#LastMinuteDress Target
target 'LastMinuteDress' do
  

  end


#Travo Target
target 'Travo' do
  

  end


#Carroai Target
target 'Carroai' do
  

  end
#WashValley Target
target 'WashValley' do
  

  end
#Tajammul Target
target 'Tajammul' do
  

  end
#CabWay Target
target 'CabWay' do
  

  end

# #VICI Target
target 'VICI' do
  

  end

#ThreadAgain Target
target 'ThreadAgain' do
  

  end

#Stonses Target
target 'Stonses' do
  

  end
#BlacNetwork Target
target 'BlacNetwork' do
  

  end


#EzMobileFuel Target
target 'EzMobileFuel' do
  

  end
#Ssuum Target
target 'Ssuum' do
  

  end

#SwiftandValu Target
target 'SwiftandValu' do
  

  end

#RunaRound Target
target 'RunaRound' do
  

  end

# #Trucxi Target
target 'Trucxi' do
  

  end

#LaundryOrders Target
target 'LaundryOrders' do
  

  end

#Groupy Target
target 'Groupy' do
  

  end
#DoctaTransportation
target 'DoctaTransportation' do
  

  end

#HairstonExpress
target 'HairstonExpress' do
  

  end

#ChipeTaxi
target 'ChipeTaxi' do
  

  end

#PaySic
target 'PaySic' do
  

  end

#NaDelivery
target 'NaDelivery' do
  

  end


#INeed
target 'INeed' do
  

  end



#BoozieDoozie
target 'BoozieDoozie' do
  

  end

#Yoho
target 'Yoho' do
  

  end


#Marasym
target 'Marasym' do
  

  end

#Mobi
target 'Mobi' do
  

  end

#SamakeeMart
target 'SamakeeMart' do
  

  end


#Baytukom
target 'Baytukom' do
  

  end


#Silvestre
target 'Silvestre' do
  

  end

#DoorStep
target 'DoorStep' do
  

  end



#Seaeats
target 'Seaeats' do
  

  end

#Enext
target 'Enext' do
  

  end

#FoodNests
target 'FoodNests' do
  

  end

#Tasmeem
target 'Tasmeem' do
  

  end

#DestinationOps
target 'DestinationOps' do
  

  end

#CannabusExpress
target 'CannabusExpress' do
  

  end

#FlyingHorse
target 'FlyingHorse' do
  

  end

#UFood
target 'UFood' do
  

  end

#Servze
target 'Servze' do
  

  end

#WeEat
target 'WeEat' do
  

  end

#GoMeat
target 'GoMeat' do
  

  end
#Shariff
target 'Shariff' do
  

  end

# #TransportSystem
target 'TransportSystem' do
  

  end
#Sambiga
target 'Sambiga' do
  

  end

#ShopCentral
target 'ShopCentral' do
  

  end

#Sponge
target 'Sponge' do
  

  end

#Skidoo
target 'Skidoo' do
  

  end


#TowFinder
target 'TowFinder' do
  

  end



#AGBDeliveries
target 'AGBDeliveries' do
  

  end

#ADMCourier
target 'ADMCourier' do
  

  end

#KurbsideKings
target 'KurbsideKings' do
  

  end

#MovingWheels
target 'MovingWheels' do
  

  end

#Safewalks
target 'Safewalks' do
  

  end

#Empire
target 'Empire' do
  

  end

#DimaVega
target 'DimaVega' do
  

  end

#Skoop
target 'Skoop' do
  

  end
#Pickmeup
target 'Pickmeup' do
  

  end
#Kudhyo
target 'Kudhyo' do
  

  end



#BharatMove
target 'BharatMove' do
  

  end

#Mozmarcas
target 'Mozmarcas' do

end
 
#Sofia
target 'Sofia' do
  

  end
#MML
target 'MML' do
  

  end


#Bimol
target 'Bimol' do
  

  end

#TripTCI
target 'TripTCI' do
  

  end


#PinkyDeli
target 'PinkyDeli' do
  

  end
#Vendoor
target 'Vendoor' do
  

  end

#Releezer
target 'Releezer' do
  

  end

#VendorSpot
target 'VendorSpot' do
  

  end

#SXM2GO
target 'SXM2GO' do
  

  end

#FarmerSouq
target 'FarmerSouq' do
  

  end

   #Easyu
target 'Easyu' do
  

  end

#CitySuds
target 'CitySuds' do

end


#Drivva
target 'Drivva' do


end

#MyFiji
target 'MyFiji' do

end

#RiteNow
target 'RiteNow' do

end

#FastMikes
target 'FastMikes' do


end

#HomeTownDeliveryllc

target 'HomeTownDeliveryllc' do

end

#Flit
target 'Flit' do

end

#Fides
target 'Fides' do

end

#Ullaz
target 'Ullaz' do

end

#Privatepremiumpickups
target 'Privatepremiumpickups' do

end

#Ihelp
target 'Ihelp' do

end

#BksTaxi
target 'BksTaxi' do

end
#Oxo
target 'Oxo' do

end
#Everywhere
target 'Everywhere' do

end
#Sijang
target 'Sijang' do

end
#CannabisClubSF
target 'CannabisClubSF' do

end

#Fairexpay
target 'Fairexpay' do

end

#KeyDiscovery
target 'KeyDiscovery' do

end

#HalaTalabat
target 'HalaTalabat' do

end

#Palmettoplus
target 'Palmettoplus' do

end

#AlloTaxi
target 'AlloTaxi' do

end


#JadorDrive
target 'JadorDrive' do

end

#KongaFood
target 'KongaFood' do

end

#UberCann
target 'UberCann' do

end

#TheHouse
target 'TheHouse' do

end

#Launch
target 'Launch' do

end


#Kampick
target 'Kampick' do

end



#BlueBolt
target 'BlueBolt' do

end

#IPicknDrop
target 'IPicknDrop' do

end

#Cabio
target 'Cabio' do

end

#Tumbak
target 'Tumbak' do

end

#MeatEasy
target 'MeatEasy' do

end

#BoltDelivery
target 'BoltDelivery' do

end

#OnTheGo
target 'OnTheGo' do

end

#MylaGlobal
target 'MylaGlobal' do

end

#GamaDelivery
target 'GamaDelivery' do

end

#AmbuTap
target 'AmbuTap' do

end

#SwiffyLLC
target 'SwiffyLLC' do

end

#Sabroson
target 'Sabroson' do

end

#Localdropoff
target 'Localdropoff' do

end

#Hivefair
target 'Hivefair' do

end

#Beakme
target 'Beakme' do

end

#Onscart
target 'Onscart' do

end

#Foodies
target 'Foodies' do

end

#Go
target 'Go' do

end

#BauBau
target 'BauBau' do

end

#BookARyde
target 'BookARyde' do

end


#ZestyClickz
target 'ZestyClickz' do

end

#YoloSonic
target 'YoloSonic' do

end

#Xborne
target 'Xborne' do

end

#LOPHT
target 'LOPHT' do

end

#Fawaz
target 'Fawaz' do

end

#Seratho
target 'Seratho' do

end

#Delivadrinks
target 'Delivadrinks' do

end

#GRN
target 'GRN' do

end

#Getfix
target 'Getfix' do

end

#MyRide
target 'MyRide' do

end

#ScoopaTechnologies
target 'ScoopaTechnologies' do

end

#Slider
target 'Slider' do

end

#ICare
target 'ICare' do

end

#Qrider
target 'Qrider' do

end

#Dlvrd
target 'Dlvrd' do

end

#Delivery
target 'Delivery' do

end

#TimHomeServices
target 'TimHomeServices' do

end

#Dbairro
target 'Dbairro' do

end

#KnockKnock
target 'KnockKnock' do

end

#HelloDeliver
target 'HelloDeliver' do

end

#ViversBox
target 'ViversBox' do

end

#Scootz
target 'Scootz' do

end

#Ola
target 'Ola' do

end

#SunShineRideShare
target 'SunShineRideshare' do

end

#spliffNation
target 'SpliffNation' do

end

#sourcesServices
target 'SourcesServices' do

end

#beachHop
target 'BeachHop' do

end

#wer
target 'Wer' do

end

#MartinOnWheels
target 'MartinOnWheels' do

end

#Qseek
target 'Qseek' do

end

#Delvento
target 'Delvento' do

end

#RideShare
target 'RideShare' do

end

#NineOneTwo
target 'NineOneTwo' do

end

#UpStreet
target 'UpStreet' do

end

#AirlinesRecruiter
target 'AirlinesRecruiter' do

end

#NewYorkMiniMart
target 'NewYorkMiniMart' do

end

#Trip
target 'Trip' do

end

#HeyBuddy
target 'HeyBuddy' do

end

#AauJau
target 'AauJau' do

end


#TmgShops
target 'TmgShops' do

end

#MediPick
target 'MediPick' do

end


#MandaExpress
target 'MandaExpress' do

end

#Meltivers
target 'Meltivers' do

end 

#EnsoDigitalAgency
target 'EnsoDigitalAgencydispatcherRelease' do

end

#HiperAbasto
target 'HiperAbasto' do

end 

#Redglee
target 'Redglee' do

end 

#CapitalDiagnostics
target 'CapitalDiagnostics' do

end 

#Dropitoffusa
target 'Dropitoffusa' do

end 

#HandyPickup
target 'HandyPickup' do

end 

#TJJHub
target 'TJJHub' do

end 

#OrbitGroup
target 'OrbitGroup' do

end 

#Cartnar
target 'Cartnar' do

end 

#Uven
target 'Uven' do

end 

#PAS41
target 'PAS41' do

end 

#Snabbhem
target 'Snabbhem' do

end 

#WaterTaxi
target 'WaterTaxi' do

end 

#FreshFarmz
target 'FreshFarmz' do

end 

#Ryde
target 'Ryde' do

end 

#Muvpod
target 'Muvpod' do

end 

#CurblerLLC
target 'CurblerLLC' do

end 

#Smile
target 'Smile' do

end 

#GasGiant
target 'GasGiant' do

end 

#CaronaTaxi
target 'CaronaTaxi' do

end 

#MarjMarketplace
target 'MarjMarketplace' do

end 

#Kazakazi
target 'Kazakazi' do

end 

#EvsOnTheGo
target 'EvsOnTheGo' do

end 

#Arwin
target 'Arwin' do

end

#PapiRuki
target 'PapiRuki' do

end

#MarkSoublet
target 'MarkSoublet' do

end

#amstaFood
target 'AmstaFood' do

end

#Toor
target 'Toor' do

end

#PeerDeliveries
target 'PeerDeliveries' do

end

#MrHealth
target 'MrHealth' do

end

#Swan
target 'Swan' do

end

#ScootUp
target 'ScootUp' do

end

#PatrolNow
target 'PatrolNow' do

end

#ButlerDelivery
target 'ButlerDelivery' do

end

#SwatiRx
target 'SwatiRx' do

end

#Maiz
target 'Maiz' do

end
#OrderFirst
target 'OrderFirst' do

end
#GinDeliver
target 'GinDeliver' do

end
#ChowHub
target 'ChowHub' do

end
#DingDongEat
target 'DingDongEat' do

end
#Medicab
target 'Medicab' do

end
#FazeiTeam
target 'FazeiTeam' do

end
#Jiffex
target 'Jiffex' do

end
#WeTogether
target 'WeTogether' do

end
#JazzyBug
target 'JazzyBug' do

end
#Keystone Deliver
target 'KeystoneDelivery' do

end

# #SavannaRags
# target 'SavannaRags' do

# end

#Amazing Taxi
target 'AmazingTaxi' do

end
#BusTaMove
target 'BusTaMove' do

end
#Valley
target 'Valley' do

end
#MyFarma
target 'MyFarma' do

end
#BlueBundles
target 'BlueBundles' do

end
#Kartandkarry
target 'Kartandkarry' do

end
#Atasktt
target 'Atasktt' do

end
#Quicklube
target 'Quicklube' do

end
#SorDelivery
target 'SorDelivery' do

end
#GrubHouse
target 'GrubHouse' do

end
#HitchDelivery
target 'HitchDelivery' do

end
#ZoodMarket
target 'ZoodMarket' do

end
#Meow
target 'Meow' do

end
#Carlitoo
target 'Carlitoo' do

end
#DingDongDelivers
target 'DingDongDelivers' do

end
#Kurs
target 'Kurs' do

end
#Torunz
target 'Torunz' do

end
#Spa
target 'Spa' do

end
end





