import { getBundleId } from "react-native-device-info";
import { appIds, shortCodes } from "../../utils/constants/DynamicAppKeys";

export const getAppCode = () => {
    switch (getBundleId()) {
        case appIds.royoDispatch: return shortCodes.royoDispatch
        case appIds.runrun: return shortCodes.runrun
        case appIds.deliverstat: return shortCodes.deliverstat
        case appIds.africanVillageMarket: return shortCodes.africanVillageMarket
        case appIds.africanize: return shortCodes.africanize
        case appIds.hemptify: return shortCodes.hemptify
        case appIds.goody: return shortCodes.goody
        case appIds.yogofood: return shortCodes.yogofood
        case appIds.arenaGrub: return shortCodes.arenaGrub
        case appIds.blipDelivery: return shortCodes.blipDelivery
        case appIds.bottomsUp: return shortCodes.bottomsUp
        case appIds.bustanFakieh: return shortCodes.bustanFakieh
        case appIds.codiner: return shortCodes.codiner
        case appIds.elog: return shortCodes.elog
        case appIds.cabdelivr: return shortCodes.cabdelivr
        case appIds.drivree: return shortCodes.drivree
        case appIds.seaChangeVending: return shortCodes.seaChangeVending
        case appIds.rxnow: return shortCodes.rxnow
        case appIds.ordercheckout: return shortCodes.ordercheckout
        case appIds.noki: return shortCodes.noki
        case appIds.ored: return shortCodes.ored
        case appIds.yourLaundryApp: return shortCodes.yourLaundryApp
        case appIds.yummidash: return shortCodes.yummidash
        case appIds.zuzuclean: return shortCodes.zuzuclean
        case appIds.loopWhole: return shortCodes.loopWhole
        case appIds.donepacked: return shortCodes.donepacked
        case appIds.careWorks: return shortCodes.careWorks
        case appIds.thubaeRides: return shortCodes.thubaeRides
        case appIds.menus: return shortCodes.menus
        case appIds.maxisdelivery: return shortCodes.maxisdelivery
        case appIds.pinkJet: return shortCodes.pinkJet
        case appIds.botSeat: return shortCodes.botSeat
        case appIds.mokabFix: return shortCodes.mokabFix
        case appIds.spidbi: return shortCodes.spidbi
        case appIds.wh: return shortCodes.wh
        case appIds.elcheregio: return shortCodes.elcheregio
        case appIds.hmc: return shortCodes.hmc
        case appIds.expressdeliverys: return shortCodes.expressdeliverys
        case appIds.fleety: return shortCodes.fleety
        case appIds.gumastas: return shortCodes.gumastas
        case appIds.dishefs: return shortCodes.dishefs
        case appIds.govachow: return shortCodes.govachow
        case appIds.jetrider: return shortCodes.jetrider
        case appIds.bilionza: return shortCodes.bilionza
        case appIds.baytukom: return shortCodes.baytukom
        case appIds.gokab: return shortCodes.gokab
        case appIds.bezalio: return shortCodes.bezalio
        case appIds.doleyPharmacy: return shortCodes.doleyPharmacy
        case appIds.taquick: return shortCodes.taquick
        case appIds.sirvu: return shortCodes.sirvu
        case appIds.klickmat: return shortCodes.klickmat
        case appIds.somame: return shortCodes.somame
        case appIds.equamd: return shortCodes.equamd
        case appIds.drus: return shortCodes.drus
        case appIds.shariff: return shortCodes.shariff
        case appIds.youChillax: return shortCodes.youChillax
        case appIds.instaShop: return shortCodes.instaShop
        case appIds.helpNowRightNow: return shortCodes.helpNowRightNow
        case appIds.agriOnline: return shortCodes.agriOnline
        case appIds.clickeat: return shortCodes.clickeat
        case appIds.tranzet: return shortCodes.tranzet
        case appIds.grub: return shortCodes.grub
        case appIds.punnet: return shortCodes.punnet
        case appIds.suel: return shortCodes.suel
        case appIds.shooraFresh: return shortCodes.shooraFresh
        case appIds.gusto: return shortCodes.gusto
        case appIds.click2Deliver: return shortCodes.click2Deliver
        case appIds.truckTireNow: return shortCodes.truckTireNow
        case appIds.voltaic: return shortCodes.voltaic
        case appIds.elixir: return shortCodes.elixir
        case appIds.ace: return shortCodes.ace
        case appIds.zest: return shortCodes.zest
        case appIds.homeric: return shortCodes.homeric
        case appIds.share: return shortCodes.share
        case appIds.yeboy: return shortCodes.yeboy
        case appIds.moboErrandsService: return shortCodes.moboErrandsService
        case appIds.Kel360: return shortCodes.Kel360
        case appIds.travo: return shortCodes.travo
        case appIds.lastMinuteDress: return shortCodes.lastMinuteDress
        case appIds.washvalley: return shortCodes.washvalley
        case appIds.tajammul: return shortCodes.tajammul
        case appIds.cabWay: return shortCodes.cabWay
        case appIds.carroai: return shortCodes.carroai
        case appIds.vici: return shortCodes.vici
        case appIds.stonses: return shortCodes.stonses
        case appIds.threadAgain: return shortCodes.threadAgain
        case appIds.blacNetwork: return shortCodes.blacNetwork
        case appIds.ezMobileFuel: return shortCodes.ezMobileFuel
        case appIds.ssuum: return shortCodes.ssuum
        case appIds.swiftandValu: return shortCodes.swiftandValu
        case appIds.runaRound: return shortCodes.runaRound
        case appIds.trucxi: return shortCodes.trucxi
        case appIds.laundryOrders: return shortCodes.laundryOrders
        case appIds.groupy: return shortCodes.groupy
        case appIds.docta_transportation: return shortCodes.docta_transportation
        case appIds.hairstonexpress: return shortCodes.hairstonexpress
        case appIds.iNeed: return shortCodes.iNeed
        case appIds.naDelivery: return shortCodes.naDelivery
        case appIds.chipeTaxi: return shortCodes.chipeTaxi
        case appIds.paySic: return shortCodes.paySic
        case appIds.boozieDoozie: return shortCodes.boozieDoozie
        case appIds.yoho: return shortCodes.yoho
        case appIds.marasym: return shortCodes.marasym
        case appIds.mobi: return shortCodes.mobi
        case appIds.samakeeMart: return shortCodes.samakeeMart
        case appIds.silvestre: return shortCodes.silvestre
        case appIds.doorstep: return shortCodes.doorstep
        case appIds.seaeats: return shortCodes.seaeats
        case appIds.enext: return shortCodes.enext
        case appIds.foodNests: return shortCodes.foodNests
        case appIds.tasmeem: return shortCodes.tasmeem
        case appIds.destination_ops: return shortCodes.destination_ops
        case appIds.cannabus_express: return shortCodes.cannabus_express
        case appIds.flying_horse: return shortCodes.flying_horse
        case appIds.ufood: return shortCodes.ufood
        case appIds.servze: return shortCodes.servze
        case appIds.goMeat: return shortCodes.goMeat
        case appIds.transportSystem: return shortCodes.transportSystem
        case appIds.shopCentral: return shortCodes.shopCentral
        case appIds.sponge: return shortCodes.sponge
        case appIds.skidoo: return shortCodes.skidoo
        case appIds.weEat: return shortCodes.weEat
        case appIds.sambiga: return shortCodes.sambiga
        case appIds.towFinder: return shortCodes.towFinder
        case appIds.aGBDeliveries: return shortCodes.aGBDeliveries
        case appIds.admCourier: return shortCodes.admCourier
        case appIds.kurbsideKings: return shortCodes.kurbsideKings
        case appIds.movingWheels: return shortCodes.movingWheels
        case appIds.safewalks: return shortCodes.safewalks
        case appIds.empire: return shortCodes.empire
        case appIds.dimaVega: return shortCodes.dimaVega
        case appIds.dummyDispatcher: return shortCodes.dummyDispatcher
        case appIds.skoop: return shortCodes.skoop
        case appIds.pickmeup: return shortCodes.pickmeup
        case appIds.kudhyo: return shortCodes.kudhyo
        case appIds.bharatMove: return shortCodes.bharatMove
        case appIds.sofia: return shortCodes.sofia
        case appIds.mml: return shortCodes.mml
        case appIds.bimol: return shortCodes.bimol
        case appIds.tripTCI: return shortCodes.tripTCI
        case appIds.vendoor: return shortCodes.vendoor
        case appIds.pinkyDeli: return shortCodes.pinkyDeli
        case appIds.releezer: return shortCodes.releezer
        case appIds.vendorSpot: return shortCodes.vendorSpot
        case appIds.SXM2GO: return shortCodes.SXM2GO
        case appIds.farmerSouq: return shortCodes.farmerSouq
        case appIds.yogo_lift: return shortCodes.yogo_lift
        case appIds.mozmarcas: return shortCodes.mozmarcas
        case appIds.stichesonSite: return shortCodes.stichesonSite
        case appIds.tmgShops: return shortCodes.tmgShops
        case appIds.gasGiant: return shortCodes.gasGiant
        case appIds.zestyClickz: return shortCodes.zestyClickz
        case appIds.citysuds: return shortCodes.citysuds
        case appIds.drivva: return shortCodes.drivva
        case appIds.easyu: return shortCodes.easyu
        case appIds.myfiji: return shortCodes.myfiji
        case appIds.ritenow: return shortCodes.ritenow
        case appIds.fastMikes: return shortCodes.fastMikes
        case appIds.hometowndeliveryllc: return shortCodes.hometowndeliveryllc
        case appIds.flit: return shortCodes.flit
        case appIds.fides: return shortCodes.fides
        case appIds.ullaz: return shortCodes.ullaz
        case appIds.privatepremiumpickups: return shortCodes.privatepremiumpickups
        case appIds.ihelp: return shortCodes.ihelp
        case appIds.bksTaxi: return shortCodes.bksTaxi
        case appIds.oxo: return shortCodes.oxo
        case appIds.everywhere: return shortCodes.everywhere
        case appIds.sijang: return shortCodes.sijang
        case appIds.fairexpay: return shortCodes.fairexpay
        case appIds.cannabis_Club_SF: return shortCodes.cannabis_Club_SF
        case appIds.martinonwheels: return shortCodes.martinonwheels
        case appIds.keydiscovery: return shortCodes.keydiscovery
        case appIds.palmettoplus: return shortCodes.palmettoplus
        case appIds.halaTalabat: return shortCodes.halaTalabat
        case appIds.alloTaxi: return shortCodes.alloTaxi
        case appIds.jadorDrive: return shortCodes.jadorDrive
        case appIds.kongaFood: return shortCodes.kongaFood
        case appIds.theHouse: return shortCodes.theHouse
        case appIds.uberCann: return shortCodes.uberCann
        case appIds.launch: return shortCodes.launch
        case appIds.kampick: return shortCodes.kampick
        case appIds.iPicknDrop: return shortCodes.iPicknDrop
        case appIds.bluebolt: return shortCodes.bluebolt
        case appIds.cabio: return shortCodes.cabio
        case appIds.tumbak: return shortCodes.tumbak
        case appIds.meateasy: return shortCodes.meateasy
        case appIds.boltDelivery: return shortCodes.boltDelivery
        case appIds.onTheGo: return shortCodes.onTheGo
        case appIds.mylaGlobal: return shortCodes.mylaGlobal
        case appIds.gamaDelivery: return shortCodes.gamaDelivery
        case appIds.ambuTap: return shortCodes.ambuTap
        case appIds.swiffyLLC: return shortCodes.swiffyLLC
        case appIds.sabroson: return shortCodes.sabroson
        case appIds.localdropoff: return shortCodes.localdropoff
        case appIds.hivefair: return shortCodes.hivefair
        case appIds.beakMe: return shortCodes.beakMe
        case appIds.onscart: return shortCodes.onscart
        case appIds.foodies: return shortCodes.foodies
        case appIds.go: return shortCodes.go
        case appIds.baubau: return shortCodes.baubau
        case appIds.bookaryde: return shortCodes.bookaryde
        case appIds.mandaExpress: return shortCodes.mandaExpress
        case appIds.yalary: return shortCodes.yalary
        case appIds.heyBuddy: return shortCodes.heyBuddy
        case appIds.petsChoice: return shortCodes.petsChoice
        case appIds.yoloSonic: return shortCodes.yoloSonic
        case appIds.mrHealth: return shortCodes.mrHealth
        case appIds.ubi: return shortCodes.ubi
        case appIds.lOPHT: return shortCodes.lOPHT
        case appIds.seratho: return shortCodes.seratho
        case appIds.xborne: return shortCodes.xborne
        case appIds.fawaz: return shortCodes.fawaz
        case appIds.gRN: return shortCodes.gRN
        case appIds.myRide: return shortCodes.myRide
        case appIds.delivadrinks: return shortCodes.delivadrinks
        case appIds.getfix: return shortCodes.getfix
        case appIds.scoopaTechnologies: return shortCodes.scoopaTechnologies
        case appIds.slider: return shortCodes.slider
        case appIds.iCare: return shortCodes.iCare
        case appIds.qrider: return shortCodes.qrider
        case appIds.dlvrd: return shortCodes.dlvrd
        case appIds.delivery: return shortCodes.delivery
        case appIds.timHomeServices: return shortCodes.timHomeServices
        case appIds.dbairro: return shortCodes.dbairro
        case appIds.knockknock: return shortCodes.knockknock
        case appIds.helloDeliver: return shortCodes.helloDeliver
        case appIds.viversBox: return shortCodes.viversBox
        case appIds.scootz: return shortCodes.scootz
        case appIds.ola: return shortCodes.ola
        case appIds.sunShineRideShare: return shortCodes.sunShineRideShare
        case appIds.spliffNation: return shortCodes.spliffNation
        case appIds.sourcesServices: return shortCodes.sourcesServices
        case appIds.beachHop: return shortCodes.beachHop
        case appIds.wer: return shortCodes.wer
        case appIds.qseek: return shortCodes.qseek
        case appIds.delvento: return shortCodes.delvento
        case appIds.rideShare: return shortCodes.rideShare
        case appIds.newYorkMiniMart: return shortCodes.newYorkMiniMart
        case appIds.airlinesRecruiter: return shortCodes.airlinesRecruiter
        case appIds.upStreet: return shortCodes.upStreet
        case appIds.nineOneTwo: return shortCodes.nineOneTwo
        case appIds.trip: return shortCodes.trip
        case appIds.tranzit: return shortCodes.tranzit
        case appIds.aauJau: return shortCodes.aauJau
        case appIds.mediPick: return shortCodes.mediPick
        case appIds.meltivers: return shortCodes.meltivers
        case appIds.ensoDigitalAgency: return shortCodes.ensoDigitalAgency
        case appIds.hiperAbasto: return shortCodes.hiperAbasto
        case appIds.redglee: return shortCodes.redglee
        case appIds.capitalDiagnostics: return shortCodes.capitalDiagnostics
        case appIds.handyPickup: return shortCodes.handyPickup
        case appIds.dropitoffusa: return shortCodes.dropitoffusa
        case appIds.tjjHub: return shortCodes.tjjHub
        case appIds.orbitGroup: return shortCodes.orbitGroup
        case appIds.cartnar: return shortCodes.cartnar
        case appIds.uven: return shortCodes.uven
        case appIds.pAS41: return shortCodes.pAS41
        case appIds.snabbhem: return shortCodes.snabbhem
        case appIds.waterTaxi: return shortCodes.waterTaxi
        case appIds.freshFarmz: return shortCodes.freshFarmz
        case appIds.ryde: return shortCodes.ryde
        case appIds.muvpod: return shortCodes.muvpod
        case appIds.curblerLLC: return shortCodes.curblerLLC
        case appIds.smile: return shortCodes.smile
        case appIds.caronaTaxi: return shortCodes.caronaTaxi
        case appIds.marjMarketplace: return shortCodes.marjMarketplace
        case appIds.evsOnTheGo: return shortCodes.evsOnTheGo
        case appIds.kazakazi: return shortCodes.kazakazi
        case appIds.arwin: return shortCodes.arwin
        case appIds.papiRuki: return shortCodes.papiRuki
        case appIds.markSoublet: return shortCodes.markSoublet
        case appIds.amstaFood: return shortCodes.amstaFood
        case appIds.toor: return shortCodes.toor
        case appIds.peerDeliveries: return shortCodes.peerDeliveries
        case appIds.swan: return shortCodes.swan
        case appIds.scootUp: return shortCodes.scootUp
        case appIds.patrolNow: return shortCodes.patrolNow
        case appIds.butlerDelivery: return shortCodes.butlerDelivery
        case appIds.swatiRx: return shortCodes.swatiRx
        case appIds.chowHub: return shortCodes.chowHub
        case appIds.ginDeliver: return shortCodes.ginDeliver
        case appIds.maiz: return shortCodes.maiz
        case appIds.orderFirst: return shortCodes.orderFirst
        case appIds.dingDongEat: return shortCodes.dingDongEat
        case appIds.medicab: return shortCodes.medicab
        case appIds.fazeiTeam: return shortCodes.fazeiTeam
        case appIds.weTogether: return shortCodes.weTogether
        case appIds.Jiffex: return shortCodes.Jiffex
        case appIds.jazzyBug: return shortCodes.jazzyBug
        case appIds.savannaRags: return shortCodes.savannaRags
        case appIds.amazingTaxi: return shortCodes.amazingTaxi
        case appIds.keystoneDelivery: return shortCodes.keystoneDelivery
        case appIds.busTaMove: return shortCodes.busTaMove
        case appIds.valley: return shortCodes.valley
        case appIds.myFarma: return shortCodes.myFarma
        case appIds.blueBundles: return shortCodes.blueBundles
        case appIds.kartandkarry: return shortCodes.kartandkarry
        case appIds.atasktt: return shortCodes.atasktt
        case appIds.quicklube: return shortCodes.quicklube
        case appIds.sorDelivery: return shortCodes.sorDelivery
        case appIds.grubHouse: return shortCodes.grubHouse
        case appIds.hitchDelivery: return shortCodes.hitchDelivery
        case appIds.zoodMarket: return shortCodes.zoodMarket
        case appIds.meow: return shortCodes.meow
        case appIds.carlitoo: return shortCodes.carlitoo
        case appIds.dingDongDelivers: return shortCodes.dingDongDelivers
        case appIds.kurs: return shortCodes.kurs
        case appIds.torunz: return shortCodes.torunz
        case appIds.spa: return shortCodes.spa
        case appIds.abbeRides: return shortCodes.abbeRides
        case appIds.nrsa: return shortCodes.nrsa
        case appIds.sadia: return shortCodes.sadia
        case appIds.elentaMart: return shortCodes.elentaMart
        case appIds.exprexpro: return shortCodes.exprexpro
        case appIds.fresHest: return shortCodes.fresHest
        case appIds.servern: return shortCodes.servern
        case appIds.smokeRun: return shortCodes.smokeRun
        case appIds.myEvPlus: return shortCodes.myEvPlus
        case appIds.pawsee: return shortCodes.pawsee
        case appIds.hairRun: return shortCodes.hairRun
        case appIds.qdelo: return shortCodes.qdelo
        case appIds.zuriRide: return shortCodes.zuriRide
        case appIds.americanLuxury: return shortCodes.americanLuxury
        case appIds.smartMur: return shortCodes.smartMur
        case appIds.ouiSpeed: return shortCodes.ouiSpeed
        case appIds.getItSent: return shortCodes.getItSent
        case appIds.iAmSelling: return shortCodes.iAmSelling
        case appIds.fifteenP: return shortCodes.fifteenP
        case appIds.euodooTechnologies: return shortCodes.euodooTechnologies
        case appIds.rota: return shortCodes.rota
        case appIds.farmMeat: return shortCodes.farmMeat
        case appIds.yallaEat: return shortCodes.yallaEat
        case appIds.choizez: return shortCodes.choizez
        case appIds.otto: return shortCodes.otto
        case appIds.rescueRoadsideAssistance: return shortCodes.rescueRoadsideAssistance
        case appIds.taxE: return shortCodes.taxE
        case appIds.baggageTaxi: return shortCodes.baggageTaxi
        case appIds.mersi: return shortCodes.mersi
        case appIds.foodSpot: return shortCodes.foodSpot
        case appIds.karibaMart: return shortCodes.karibaMart
        case appIds.sourceWith: return shortCodes.sourceWith
        case appIds.vdu: return shortCodes.vdu
        case appIds.taxiology: return shortCodes.taxiology
        case appIds.laundroZone: return shortCodes.laundroZone
        case appIds.swipe: return shortCodes.swipe
        case appIds.sheRyders: return shortCodes.sheRyders
        case appIds.kurrix: return shortCodes.kurrix
        case appIds.easyDrink: return shortCodes.easyDrink
        case appIds.mrVeloz: return shortCodes.mrVeloz
        case appIds.pets: return shortCodes.pets
        case appIds.greenCab: return shortCodes.greenCab
        case appIds.axxi: return shortCodes.axxi
        case appIds.shelf: return shortCodes.shelf
        case appIds.getDress: return shortCodes.getDress
        case appIds.nuvoni: return shortCodes.nuvoni
        case appIds.fairDeal: return shortCodes.fairDeal
        case appIds.balyDlvry: return shortCodes.balyDlvry
        case appIds.hezniTaxi: return shortCodes.hezniTaxi
        case appIds.onTheWheel: return shortCodes.onTheWheel
        case appIds.valleyMeats: return shortCodes.valleyMeats
        case appIds.perucabs: return shortCodes.perucabs
        case appIds.hafizjwlry: return shortCodes.hafizjwlry
        case appIds.jana: return shortCodes.jana
        case appIds.myWayBill: return shortCodes.myWayBill
        case appIds.cattch: return shortCodes.cattch
        case appIds.tezras: return shortCodes.tezras
        case appIds.eureka: return shortCodes.eureka
        case appIds.kaypee: return shortCodes.kaypee
        case appIds.hitaxi: return shortCodes.hitaxi
        case appIds.kwivar: return shortCodes.kwivar
        case appIds.parcel: return shortCodes.parcel
        case appIds.lex: return shortCodes.lex
        case appIds.flank: return shortCodes.flank
        case appIds.smokyKitchen: return shortCodes.smokyKitchen
        case appIds.zynoride: return shortCodes.zynoride
        case appIds.mealsarehere: return shortCodes.mealsarehere
        case appIds.loamscape: return shortCodes.loamscape
        case appIds.delcolink: return shortCodes.delcolink
        case appIds.youSmokeShop: return shortCodes.youSmokeShop
        case appIds.sylomart: return shortCodes.sylomart
        case appIds.doober: return shortCodes.doober
        case appIds.inmotion: return shortCodes.inmotion
        case appIds.jeevann: return shortCodes.jeevann
        case appIds.novamed: return shortCodes.novamed
        case appIds.eatHalal: return shortCodes.eatHalal
        case appIds.awamer: return shortCodes.awamer
        case appIds.goTech: return shortCodes.goTech
        case appIds.idrv: return shortCodes.idrv
        case appIds.qwiker: return shortCodes.qwiker
        case appIds.spryton: return shortCodes.spryton
        case appIds.nittosadai: return shortCodes.nittosadai
        case appIds.clickOkart: return shortCodes.clickOkart
        case appIds.verz: return shortCodes.verz
        case appIds.tiimo: return shortCodes.tiimo
        case appIds.carryFood: return shortCodes.carryFood
        case appIds.ragioMigo: return shortCodes.ragioMigo
        case appIds.jimsAutoRescue: return shortCodes.jimsAutoRescue
        case appIds.nhazi: return shortCodes.nhazi
        case appIds.petverse: return shortCodes.petverse
        case appIds.clickNDrop: return shortCodes.clickNDrop
        case appIds.appi: return shortCodes.appi
        case appIds.lifeHomeFit: return shortCodes.lifeHomeFit
        case appIds.dbairro_: return shortCodes.dbairro_
        case appIds.genee: return shortCodes.genee
        case appIds.speedyDelivery: return shortCodes.speedyDelivery
        case appIds.holla: return shortCodes.holla
        case appIds.icabPro: return shortCodes.icabPro
        case appIds.uberWeeds: return shortCodes.uberWeeds
        case appIds.stabex: return shortCodes.stabex
        case appIds.pointoneExpediteDelivery: return shortCodes.pointoneExpediteDelivery
        case appIds.saamanShop: return shortCodes.saamanShop
        case appIds.tdc: return shortCodes.tdc
        case appIds.pik: return shortCodes.pik
        case appIds.flyCommerce: return shortCodes.flyCommerce
        case appIds.motina: return shortCodes.motina
        case appIds.greenHippo: return shortCodes.greenHippo
        case appIds.hungry: return shortCodes.hungry
        case appIds.myMeddy: return shortCodes.myMeddy
        case appIds.uRyd: return shortCodes.uRyd
        case appIds.happySingh: return shortCodes.happySingh
        case appIds.vital: return shortCodes.vital
        case appIds.parcelWorks: return shortCodes.parcelWorks
        case appIds.konectame: return shortCodes.konectame
        case appIds.usVetsDeliver: return shortCodes.usVetsDeliver
        case appIds.bigbayong: return shortCodes.bigbayong
        case appIds.locate: return shortCodes.locate
        case appIds.todaysDeliverys: return shortCodes.todaysDeliverys
        case appIds.georgiacollective: return shortCodes.georgiacollective
        case appIds.lincshare: return shortCodes.lincshare
        case appIds.rumbella: return shortCodes.rumbella
        case appIds.glavour: return shortCodes.glavour  
        case appIds.shipmoe: return shortCodes.shipmoe
        case appIds.skyline: return shortCodes.skyline
        case appIds.rentzy: return shortCodes.rentzy
        case appIds.bliss: return shortCodes.bliss
        case appIds.otgWeeds: return shortCodes.otgWeeds
        case appIds.zyno: return shortCodes.zyno
        case appIds.efectibo: return shortCodes.efectibo
        case appIds.hectoHomes: return shortCodes.hectoHomes
        case appIds.glamguide: return shortCodes.glamguide
        case appIds.sooq: return shortCodes.sooq
        case appIds.superpana: return shortCodes.superpana
        case appIds.solace: return shortCodes.solace
        case appIds.kero: return shortCodes.kero
        case appIds.housingSubsidies: return shortCodes.housingSubsidies
        case appIds.bocch: return shortCodes.bocch
        case appIds.potolo: return shortCodes.potolo
        case appIds.earnApp: return shortCodes.earnApp
        case appIds.aredoo: return shortCodes.aredoo
        case appIds.bukam: return shortCodes.bukam
        case appIds.shopcart: return shortCodes.shopcart
        case appIds.dot: return shortCodes.dot
        case appIds.wizsonic: return shortCodes.wizsonic
        case appIds.udkay: return shortCodes.udkay
        case appIds.hattaFoodHub: return shortCodes.hattaFoodHub
        case appIds.ondgoo: return shortCodes.ondgoo
        case appIds.junkerz: return shortCodes.junkerz
        case appIds.viralClean: return shortCodes.viralClean
        case appIds.messiaa: return shortCodes.messiaa
        case appIds.superApp: return shortCodes.superApp
        case appIds.nounou: return shortCodes.nounou
        case appIds.laith: return shortCodes.laith
        case appIds.oaks: return shortCodes.oaks
        case appIds.buzyStores: return shortCodes.buzyStores
        case appIds.etiam: return shortCodes.etiam
        case appIds.dotTaxi: return shortCodes.dotTaxi
        case appIds.airvoltTaxi: return shortCodes.airvoltTaxi
        case appIds.melak: return shortCodes.melak
        case appIds.vialteran: return shortCodes.vialteran
        case appIds.wiEnergi: return shortCodes.wiEnergi
        case appIds.whatChaGotPckUp: return shortCodes.whatChaGotPckUp
        case appIds.nannyAfrica: return shortCodes.nannyAfrica
        case appIds.gokart: return shortCodes.gokart
        case appIds.hqi: return shortCodes.hqi
        case appIds.nool: return shortCodes.nool
        case appIds.weemoov: return shortCodes.weemoov
        case appIds.rally: return shortCodes.rally
        case appIds.shipsmart: return shortCodes.shipsmart
        case appIds.weedLomo: return shortCodes.weedLomo
        case appIds.nGoal: return shortCodes.nGoal
        case appIds.tkaff: return shortCodes.tkaff
        case appIds.livraizoo: return shortCodes.livraizoo
        case appIds.boozeBrothers: return shortCodes.boozeBrothers
        case appIds.readyToRent: return shortCodes.readyToRent
        case appIds.theGenie: return shortCodes.theGenie
        case appIds.sultanCenter: return shortCodes.sultanCenter

        default: return '1da2e9'
    }
}