export default {
  LOGIN: 'login',
  WEBLINKS: 'Webview',
  OTP_VERIFICATION: 'OtpVerfication',
  OUTER_SCREEN: 'outerScreen',
  SIGN_UP: 'signUp',
  SHORT_CODE: 'shortCode',
  SEND_OTP: 'SendOtp',
  DASHBOARD: 'Dashboard',
  MYPROFILE: 'MyProfile',
  TASKSTACK: 'TaskStack',
  TASKHISTORY:'TaskHistory',
  PROFILESTACK: 'ProfileStack',
  DRAWER_ROUTES: 'DrawerRoutes',
};
